const ENV_GRAPHQL_PATH = process.env.GRAPHQL_PATH
const ENV_PORT = process.env.PORT
const ENV_LOGGER_LEVEL = process.env.LOGGER_LEVEL

const ENV_MOVIE_DB_API_V4_KEY = process.env.MOVIE_DB_API_V4_KEY
const ENV_MOVIE_DB_API_V3_KEY = process.env.MOVIE_DB_API_V3_KEY

const ENV_USE_CF_KV = process.env.USE_CF_KV

export {
  ENV_GRAPHQL_PATH as GRAPHQL_PATH,
  ENV_PORT as PORT,
  ENV_LOGGER_LEVEL as LOGGER_LEVEL,
  ENV_MOVIE_DB_API_V4_KEY as MOVIE_DB_API_V4_KEY,
  ENV_MOVIE_DB_API_V3_KEY as MOVIE_DB_API_V3_KEY,
  ENV_USE_CF_KV as USE_CF_KV
}
